server:
  port: 8080
  servlet:
    context-path: /test
   
spring:

  jpa:
     
    hibernate:
      ddl-auto: create    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect



  application:
    name: user-service
 
  datasource:
    url: jdbc:mysql://localhost:3306/student_db?createDatabaseIfNotExist=true
   
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
