server:
  port: 8080
  servlet:    context-path: /test
    
spring:  application:    name: user-service
  
  datasource:    url: jdbc:mysql://localhost:3306/student_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    
    
    
    
    
    
  

  